# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Mar 20 20:34:24 2020
# ------------------------------------------------

package:
    name: allensdk
    version: 2.14.4

build:

requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - alabaster 0.7.12 py_0
        - attrs 19.3.0 py_0
        - babel 2.8.0 py_0
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py36h9f0ad1d_1
        - cffi 1.14.0 py36hd463f26_0
        - chardet 3.0.4 py36h9f0ad1d_1006
        - cryptography 2.8 py36h45558ae_2
        - docutils 0.16 py36h9f0ad1d_1
        - idna 2.9 py_1
        - imagesize 1.2.0 py_0
        - importlib-metadata 1.5.0 py36h9f0ad1d_1
        - importlib_metadata 1.5.0 1
        - jinja2 2.11.1 py_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - markupsafe 1.1.1 py36h8c4c3a4_1
        - more-itertools 8.2.0 py_0
        - ncurses 6.1 hf484d3e_1002
        - numpydoc 0.9.2 py_0
        - openssl 1.1.1e h516909a_0
        - packaging 20.1 py_0
        - pip 20.0.2 py_2
        - pluggy 0.12.0 py_0
        - py 1.8.1 py_0
        - pycparser 2.20 py_0
        - pygments 2.6.1 py_0
        - pyopenssl 19.1.0 py_1
        - pyparsing 2.4.6 py_0
        - pysocks 1.7.1 py36h9f0ad1d_1
        - pytest 5.4.1 py36h9f0ad1d_0
        - pytest-runner 5.2 py_0
        - python 3.6.10 h9d8adfe_1009_cpython
        - python_abi 3.6 1_cp36m
        - pytz 2019.3 py_0
        - readline 8.0 hf8c457e_0
        - requests 2.23.0 pyh8c360ce_2
        - setuptools 46.0.0 py36h9f0ad1d_2
        - six 1.14.0 py_1
        - snowballstemmer 2.0.0 py_0
        - sphinx 2.4.4 py_0
        - sphinxcontrib-applehelp 1.0.2 py_0
        - sphinxcontrib-devhelp 1.0.2 py_0
        - sphinxcontrib-htmlhelp 1.0.3 py_0
        - sphinxcontrib-jsmath 1.0.1 py_0
        - sphinxcontrib-qthelp 1.0.3 py_0
        - sphinxcontrib-serializinghtml 1.1.4 py_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - urllib3 1.25.7 py36h9f0ad1d_1
        - wcwidth 0.1.8 py_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h516909a_1002
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h516909a_1006
    run:
        - future >=0.14.3
        - h5py >=2.3.1
        - jinja2 >=2.7.3
        - matplotlib >=1.4.3
        - numpy >=1.12.1
        - pandas >=0.16.2,<0.20.0
        - pynrrd >=0.2.1
        - python >=3.6,<3.7.0a0
        - python_abi 3.6.* *_cp36m
        - requests
        - requests-toolbelt
        - scikit-image >=0.13.0
        - scipy >=0.15.1
        - simplejson >=3.10.0
        - six >=1.9.0
        - statsmodels >=0.8.0
test:
    imports:
        - allensdk
about:
    description: 'The Allen Software Development Kit houses source code for reading
        and

        processing Allen Brain Atlas data. The Allen SDK focuses on the Allen Brain
        Observatory,

        Cell Types Database, and Mouse Brain Connectivity Atlas.

        '
    dev_url: https://github.com/AllenInstitute/AllenSDK
    home: http://alleninstitute.github.io/AllenSDK/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: core libraries for the allensdk.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - umarbrowser
